name: shelfy
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: ^3.3.4

dependencies:
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_multipart: ^1.0.0
  shelf_web_socket: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
